//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_menu
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> Seq { get; set; }
        public Nullable<int> Type { get; set; }
        public int Level { get; set; }
        public string Parent { get; set; }
        public string Url { get; set; }
        public string IconCls { get; set; }
        public string Title { get; set; }
        public bool Visible { get; set; }
        public bool Enable { get; set; }
        public string CreatePerson { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdatePerson { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
