//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MU.DBWapper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_user
    {
        public string UserCode { get; set; }
        public string UserSeq { get; set; }
        public string UserName { get; set; }
        public string Description { get; set; }
        public string Password { get; set; }
        public string RoleName { get; set; }
        public string OrganizeName { get; set; }
        public string DepCode { get; set; }
        public string ConfigJSON { get; set; }
        public bool IsEnable { get; set; }
        public int LoginCount { get; set; }
        public System.DateTime LastLoginDate { get; set; }
        public string CreatePerson { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdatePerson { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string FactoryCode { get; set; }
        public string DepNo { get; set; }
        public string Token { get; set; }
    }
}
