//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MU.DBWapper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_role
    {
        public string RoleCode { get; set; }
        public string RoleSeq { get; set; }
        public string RoleName { get; set; }
        public string Description { get; set; }
        public string CreatePerson { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdatePerson { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string CheckType { get; set; }
        public string LoginPage { get; set; }
        public string LoginFirstPage { get; set; }
    }
}
